sonar.projectKey=Alpha-Explora_toone124235
sonar.projectName=toone124235
sonar.sources=src
sonar.tests=src,tests
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.spec.tsx,**/*.test.tsx
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.spec.ts,**/*.test.ts,**/*.spec.tsx,**/*.test.tsx